# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "nfra/kickstart-flavor-pandoc:2"


command:
  dev: |
    pandoc -o _out/document.pdf \
          --defaults defaults.yaml \
          --pdf-engine=xelatex \
          --file-scope \
          --filter=pandoc-plantuml \
          --filter=pandoc-xnos \
          --filter=pandoc-citeproc

