#
# See all options: https://pandoc.org/MANUAL.html#default-files

from: markdown+emoji

output-file: output.pdf
input-files:
  - "10-chapter-one/chapter-one.md"
  - "20-chapter-two/chapter-two.md"
  - "99-appendix/appendix.md"

standalone: true
self-contained: false

variables:
  documentclass: report


glossary: true

table-of-contents: true
toc-depth: 2
number-sections: true
section-divs: true
#citeproc: true
csl: _conf/ieeeurl.csl
bibliography:
- "_conf/bib.bib"

reference-links: true


# citation-abbreviations: abbrevs.json